### ISSUE TITLE
Could not find 'sfBlazor' in 'window'.

### ISSUE THREAD

**Issue by ahmetsekmen** [syncfusion/blazor-samples#93] opened 2020-05-01 16:30 UTC
I really like this project side bar and top menu template
So have made webassemly version . i have referanced all content
I am getting this error while loading,

![image](https://user-images.githubusercontent.com/10855574/80821338-30273600-8be1-11ea-8a85-35f144ca54fa.png)

When i have searched on google it brings me al version of sycnfusion blazor lib.(ej2)

Problem comes with mainlayout.razor

here is my repo : https://github.com/ahmetsekmen/DemoAPP

**Comment by sridurgha** [comment] 2020-05-04 13:04
Hi @ahmetsekmen ,

Greetings from Syncfusion.

Sorry for the inconvenience caused. We have validated the reported issue and confirmed the same as bug. The fix for this issue will be available in the patch release scheduled on 12th May, 2020 until then we appreciate your patience.

The status of the issue can be tracked from the below mentioned feedback link.

https://www.syncfusion.com/feedback/14057/exception-is-thrown-in-client-side-application-during-the-initial-rendering-in 

Please let us know if you have any concerns.

**Comment by jesusarockias** [comment] 2020-05-13 12:25
Hi @ahmetsekmen ,

We are glad to announce that our Essential Studio 2020 Volume 1 SP release v18.1.0.52  is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/154238/essential-studio-2020-volume-1-service-pack-release-v18-1-0-52-is-available-for-download

We thank you for your support and appreciate your patience in waiting for this release. We have include the fix for the “Initial Rendering issue of Grid Template in Blazor WASM app”  with the Nuget package version “18.1.0.52” and you can find the corresponding feedback below.

Feedback: https://www.syncfusion.com/feedback/14057/exception-thrown-in-client-side-application-during-the-initial-rendering-in-grid

NuGet: https://www.nuget.org/packages/Syncfusion.Blazor/18.1.0.52

Please get in touch with us if you would require any further assistance.

**Comment by colmardev** [comment] 2020-05-14 16:04
I have same issue on WASM Core Hosted project with nuget 18.1.0.52 and v3.2.0-rc1.20223.4:

> Microsoft.JSInterop.JSException: Could not find 'sfBlazor' in 'window'.
Error: Could not find 'sfBlazor' in 'window'.
    at https://localhost:44344/_framework/blazor.webassembly.js:1:9198
    at Array.forEach (<anonymous>)
    at p (https://localhost:44344/_framework/blazor.webassembly.js:1:9158)
    at https://localhost:44344/_framework/blazor.webassembly.js:1:9868
    at new Promise (<anonymous>)

code simple as this:

`    <div id="container">
        <SfGrid DataSource="@listaServizi" AllowSelection="true" AllowSorting="true">
            <GridColumns>
                <GridColumn Field="Descrizione" />
            </GridColumns>
        </SfGrid>
    </div>`

where `listaServizi` is `List<Servizio>`

while binding in same page to Textbox works fine:

` @foreach (var servizio in listaServizi)
    {
        <Syncfusion.Blazor.Inputs.SfTextBox @bind-Value="servizio.Descrizione" />
    }`

Am I missing something?

**Comment by Pethical** [comment] 2020-05-16 12:01
Hi @sridurgha ,
I have the same issue with SfTextBox, SfButton and SfProgressBar
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'sfBlazor' in 'window'.
      Error: Could not find 'sfBlazor' in 'window'.
          at https://localhost:44306/_framework/blazor.webassembly.js:1:9198
          at Array.forEach (<anonymous>)
          at p (https://localhost:44306/_framework/blazor.webassembly.js:1:9158)
          at https://localhost:44306/_framework/blazor.webassembly.js:1:9868
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44306/_framework/blazor.webassembly.js:1:9841)
          at _mono_wasm_invoke_js_marshalled (https://localhost:44306/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171346)
          at do_icall (wasm-function[6049]:0x111976)
          at do_icall_wrapper (wasm-function[1896]:0x52c3e)
          at interp_exec_method (wasm-function[1120]:0x25a03)
```

**Comment by jesusarockias** [comment] 2020-05-18 09:13
Hi @Pethical & @colmardev ,

Sorry for the inconvenience caused. 

We have checked the reported issue and we are not able to reproduce it in our end. We have prepared a sample and video of screen capture for your reference. We are checking with VS2019 16.6 Preview 6 and we suggest you to update VS2019 before checking.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/BlazorApp1805-191618082

Video: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sfblazor-1327391900

Reference Images:

![image](https://user-images.githubusercontent.com/41784897/82195439-eeeb9180-9915-11ea-8ff2-38f5734a165e.png)
 

![image](https://user-images.githubusercontent.com/41784897/82195332-c794c480-9915-11ea-8737-da0dc956222e.png)

 

We request to share more details of this issue for clear understanding if we misunderstood your point.

Please get back to us if you need any further assistance on this.

Regards,
Jesus Arockia Sankaran S

**Comment by T-Alkathiri** [comment] 2020-05-27 09:58
I have downloaded the above giving example it runs good with out any error, then i update all the webassemply to the official resales versions :
Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.0"
Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0" PrivateAssets="all"
Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0" PrivateAssets="all"
 also works good.
But when i updated the Syncfusion.Blazor to Version="18.1.0.54 then i got the same error
Could not find 'sfBlazor' in 'window'.
Could you please fix this bug with the new version.
Thank you very much.

**Comment by Pethical** [comment] 2020-05-27 10:20
@colmardev 
Thank you,
Yes, this is fixed my issues. I changed
```
builder.Services.AddSyncfusionBlazor(true);
```
to
```
builder.Services.AddSyncfusionBlazor(false);
```
and now everything is working fine.

**Comment by Pethical** [comment] 2020-05-27 10:36
Yes, it works fine with 18.1.0.52, but not with 18.1.0.54.
Thank you very much.
(I tried in vs2019 16.6, vs2019 16.7 preview)
Thank you!

**Comment by rajeshjha96** [comment] 2020-05-28 07:57
Yes, it does not works with 18.1.0.54.
Kindly solve this.

**Comment by ajithr** [comment] 2020-05-28 10:57
Hi @T-Alkathiri , @Pethical , @rajeshjha96 ,

We are sorry for the inconvenience caused. We are able to reproduce the reported issue in Blazor WebAssembly application with v18.1.0.54. We will resolve the issue and include the fix in the next patch release which is expected to release on June 02, 2020.
 
As of now, please use the below workaround to resolve the issue.

1. Set true to the SyncfusionBlazorService in `~/Program.cs`.

```
builder.Services.AddSyncfusionBlazor(true);
```

2. Add Syncfusion interop script file manually in `~/wwwroot/index.html` file.
```
<head>
   .....
   .....
  <script src="_content/Syncfusion.Blazor/scripts/syncfusion-blazor.min.js" type="text/javascript"></script>
</head>
```
Please let us know if you need any further assistance on this.

Regards,
Ajith R

**Comment by rajeshjha96** [comment] 2020-05-28 13:19
Thanks. It worked!!!!

**Comment by T-Alkathiri** [comment] 2020-05-29 07:12
For me it did not work
it gives me this error: 
(syncfusion-blazor.min.js:1 Cannot read property 'appendChild' of null
TypeError: Cannot read property 'appendChild' of null)

**Comment by icsilambarasan** [comment] 2020-06-02 17:01
Hi @T-Alkathiri , @Pethical  and @rajeshjha96 ,

The reported issue “_Error: Could not find 'sfBlazor' in 'window'_” in Blazor WebAssembly application with v18.1.0.54 has been fixed and included the fix in our latest patch release (v18.1.0.55). Please upgrade our package to the latest version to resolve this issue.

_NuGet package:_
[Syncfusion.Blazor](https://www.nuget.org/packages/Syncfusion.Blazor/18.1.0.55)

**Comment by T-Alkathiri** [comment] 2020-06-03 04:31
Thank you very mcuh.

**Comment by Pethical** [comment] 2020-06-03 06:32
Thank you!

**Closed** 2020-06-04 12:05 UTC
Labels: common
