### ISSUE TITLE
Missing Flags Attribute for Enum NodeConstraints 

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#22] opened 2019-06-15 16:51 UTC
For all Constraint Enums i saw the"Flags" Attribute is missing. So the Bitwise Operation in C# does not work. Example: NodeConstraints

**Comment by RamyaThiru** [comment] 2019-06-17 10:14
Hi @endeffects ,

We are unable to reproduce the issue with NodeConstraints. it is the flagged enum and the bitwise operation is working fine. We have provided the code example and sample to represent this.

For example, we have restricted the drag operation of node using NodeConstraints and bit wise operation. 

Code example:
<EjsDiagram id="diagram" ref="diagram" Width="100%" Height="690px"> 
            <DiagramNodes>
                @*Disable dragging for an node*@
                <DiagramNode Id="node1" Width="100" Height="100" OffsetX="200" OffsetY="200" Constraints="NodeConstraints.Default &~NodeConstraints.Drag">
                </DiagramNode>
            </DiagramNodes>
        </EjsDiagram>


Sample Link: http://www.syncfusion.com/downloads/support/directtrac/general/ze/NodeConstraintsSample-1800239135

Regards,
Ramya T

**Comment by endeffects** [comment] 2019-06-17 10:17
Thanks for your reply. Yes, It works in the markup as in your example.
But my problem is related to the code behind (pure c#).

**Comment by endeffects** [comment] 2019-06-17 17:34
I've created a screenshot:
![image](https://user-images.githubusercontent.com/13432569/59624382-e81d3300-9136-11e9-9d2c-c3de2a63a066.png)

**Comment by RamyaThiru** [comment] 2019-06-18 08:51
Hi ,

Reported issue : Bitwise operation on enum which is not marked by flag attribute.

We were unable to replicate the reported issue when specifying NodeConstraints as var data type. But we are facing another issue when assigning the NodeConstraints enum value to an ‘var’ datatype. We have provided screenshot as below to represent the issue. 

Screenshot:
![image](https://user-images.githubusercontent.com/5535468/59667358-3d5b5200-91d4-11e9-87d5-1794b26dd6e8.png)

Please set NodeConstraints value to an NodeConstraints enum type as shown in code example to resolve this issue. We have provided sample to represent the solution. Please refer to the sample from the below link.

Sample: http://www.syncfusion.com/downloads/support/directtrac/general/ze/NodeConstraintsCSharpSample-732055733

Code example:

<EjsDiagram ref="diagram" id="diagram" Width="1000" Height="1000"> 
            <DiagramNodes>
                @*define node constraints*@
                <DiagramNode Id="Inventor" Constraints="@Constraints" Height="100" Width="100" OffsetX="200" OffsetY="200"> 
                </DiagramNode> 
            </DiagramNodes> 
        </EjsDiagram>

@functions{ 
    EjsDiagram diagram;

    //enables select, rotate and resize for node.
    NodeConstraints Constraints = NodeConstraints.PointerEvents | NodeConstraints.Select | NodeConstraints.Rotate | NodeConstraints.Resize;

}

Regards,
Ramya T

**Comment by endeffects** [comment] 2019-06-18 16:49
I tried your example too, but i i have the error in the base class and the function mark up code.
Maybe it is related to the resharper i'm using or my version is outdated (17.1.0.51-beta).

![image](https://user-images.githubusercontent.com/13432569/59703087-70fca300-91f9-11e9-8e68-941c2fc5572a.png)

**Comment by RamyaThiru** [comment] 2019-06-19 12:59
Hi @endeffects,

We have considered this as an enhancement with Constraints enum. We have logged the report for this scenario. We will implement and include this support in our Volume 3 release on October 2019. We will get back to you once our Volume 3 is released.

Now, you can track the status of your request through the below feedback link.

Link: https://www.syncfusion.com/feedback/7007/missing-flags-attribute-for-enum-constraints

Regards,
Ramya T

**Comment by endeffects** [comment] 2019-06-19 13:00
Thank you :)

**Comment by Sridhar-Narasimhan** [comment] 2020-04-29 08:13
We have fixed this issue in the below feedback link and we are closing this item.
Feedback Link:  https://www.syncfusion.com/feedback/7007/missing-flags-attribute-for-enum-constraints

**Closed** 2020-04-29 08:13 UTC
Labels: diagram
