### ISSUE TITLE
How to get the index or the data of the row in the grid?

### ISSUE THREAD

**Issue by YordanYanakiev** [syncfusion/blazor-samples#74] opened 2019-11-07 13:59 UTC
Is it possible to get the index of the dataSource of the current row, or the data of the current row somehow with EjsGrid ?
As well - why the button does not visualize ? is it a bug, or there is something else which must be done ?

```
<EjsGrid DataSource="@GridData" ModelType="@Model" Toolbar="@(new List<string>() { "Add", "Edit", "Delete", "Update", "Cancel" })" AllowPaging="true" >
                    <GridEditSettings AllowAdding="false" AllowDeleting="false" AllowEditing="true"></GridEditSettings>
                    <GridColumns>
                        <GridColumn Field=@nameof( WordDataModel.keyWord ) HeaderText="KeyWord" IsPrimaryKey="true" Width="140"></GridColumn>
                        <GridColumn Field=@nameof( WordDataModel.original ) HeaderText="Original" Width="150" AllowEditing="false"></GridColumn>

                        <GridColumn Field=@nameof( WordDataModel.translation ) HeaderText="Translation" Width="140"></GridColumn>
                        <GridColumn Field=@nameof( WordDataModel.reviewRequired ) HeaderText="Review Req" Width="160" AllowEditing="false"></GridColumn>

                        <GridColumn HeaderText="Auto Translate" Width="120">
                            <Template>
                                <button @onclick="@btnClick">Auto Translate</button>
                            </Template>
                        </GridColumn>

                    </GridColumns>
                </EjsGrid>
```

**Comment by renjithsingh-rajendran123** [comment] 2019-11-08 08:58
Hi Yordan,

**Query 1 : Get index of current row, or the data of the current row**
We suggest you to use the **“GetSelectedRowIndexes”** or **“GetSelectedRecords”** methods of Grid to fetch the index or data of the current selected row. Please use the code below,

```
<EjsGrid @ref="GridInstance" DataSource="@Orders" ModelType="@Model" ...>
    <GridEditSettings AllowAdding="false" AllowDeleting="false" AllowEditing="true"></GridEditSettings>
    <GridColumns>
        ...
        <GridColumn HeaderText="Auto Translate" Width="120">
            <Template>
                <button @onclick="@btnClick">Auto Translate</button>
            </Template>
        </GridColumn>
    </GridColumns>
</EjsGrid>
@code{
    EjsGrid<Order> GridInstance;
    public List<Order> Orders { get; set; }
    public Order Model = new Order();
    public async void btnClick()
    {
        var selectedrowindex = await GridInstance.GetSelectedRowIndexes();      //Get the current selected row's index
        var selectedrowdata = await GridInstance.GetSelectedRecords();          //Get the current selected row's  data 
    }
    ...
}
```
Documentations : 
https://help.syncfusion.com/cr/aspnetcore-blazor/Syncfusion.EJ2.Blazor~Syncfusion.EJ2.Blazor.Grids.EjsGrid%601~GetSelectedRecords.html
https://help.syncfusion.com/cr/aspnetcore-blazor/Syncfusion.EJ2.Blazor~Syncfusion.EJ2.Blazor.Grids.EjsGrid%601~GetSelectedRowIndexes.html

**Query 2 : why the button does not visualize ? is it a bug,** 
We tried to reproduce this problem by preparing a sample with the shared codes. We could not reproduce the reported issue, the button renders fine in Grid’s column. We are attaching the sample which we have tried from our side for your convenience. Please download the sample from the link below,
Sample : https://www.syncfusion.com/downloads/support/directtrac/general/ze/SynfusionTest1946968859

If you are still facing difficulties, kindly share with us the following details for better assistance.
1.	Share with us the Syncfusion version details you are using.
2.	Share the sample which you have tried from your side.
3.	Share the exact scenario or proper replication procedure.
4.	Share with us the details of script error, if any occurred in the browser console.

The provided information will help us analyze the problem, and provide you a solution as early as possible.

**Comment by YordanYanakiev** [comment] 2019-11-11 07:23
By some reason it wasnt initializing. I've did a lot of tests, and finally it worked. Still wonder what was the cause.

**Comment by ajithr** [comment] 2020-12-04 03:29
We hope your reported issue has been resolved now and we are closing this issue. Feel free to reopen the issue and update your comments for the reinvestigation.

**Closed by ajithr** 2020-12-04 03:29 UTC
Labels: data-grid
