### ISSUE TITLE
Palette Refresh Issue

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#37] opened 2019-06-27 19:15 UTC
I'm trying to expand / collaps a palette at runtime.
I have a required palette and an optional one.

```
            requiredPalette = new SymbolPalettePalette
            {
                Id = "requiredPalette",
                Title = "",
                Expanded = true,
                Symbols = new List<object>
                {
                    // some nodes
                }
            };

            optionalPalette = new SymbolPalettePalette
            {
                Id = "optionalPalette",
                Title = "",
                Expanded = false, // Default is collapsed
                Symbols = new List<object>
                {
                    // some nodes
                }
            };

```

By clicking a button i'd like to collaps / expand the optional palette,
so i tried the following:

```
            optionalPalette.Expanded = !optionalPalette.Expanded;
            optionalPalette.Refresh();

            // base is the EjsSymbolPalette instance

            base.Render(); 
            base.Refresh();
```

Each time i run the code new instances of the optional and required
Palettes are added to the DOM. Also all new instances and especially
the optionalPalette are getting not rendered and staying invisible.

![image](https://user-images.githubusercontent.com/13432569/60293790-3e048e80-9920-11e9-86de-187f9e900006.png)

I also tried to add remove the optional palette to the palette collection, 
but i had a similar effect. Is this a bug?

**Comment by RamyaThiru** [comment] 2019-06-28 08:53
Hi @endeffects,

Reported issue: Palette group instance get duplicated when expand and collapse the palette group.

We can reproduce the reported issue. We will fix the issue and include it in our Volume 2 main release on July 2019.   

This issue can be tracked through the below feedback link.
Link: https://www.syncfusion.com/feedback/7175/palette-group-instance-get-duplicated-when-expand-and-collapse-that-palette-group

We will get back to you once our Volume 2 main release is rolled out.

Regards, 
Ramya T

**Comment by endeffects** [comment] 2019-06-28 08:59
Thank you.

**Comment by endeffects** [comment] 2019-06-28 09:08
That the programmatically expanded palettes got not rendered is related to the bug too, or?

**Comment by endeffects** [comment] 2019-06-28 15:36
I got an other issue here, depending on the optionalPalette State i'd like to change the size of the whole palette collection. This basically works with one drawback, the palette gets expanded but the optionalPalette will not be shown. I have to refresh the page to get it working. Also i'm receiving following error in console:

![image](https://user-images.githubusercontent.com/13432569/60353890-49f95a80-99cb-11e9-8523-acbf752f00aa.png)

```
        public async Task AdjustPalette()
        {
            optionalPalette.Expanded = !optionalPalette.Expanded;

            this.AdjustSize();
            base.StateHasChanged();

            await Task.CompletedTask;
        }
```

**Comment by RamyaThiru** [comment] 2019-07-01 11:19
Hi @endeffects ,

Thanks for sharing the sample to represent the issue.

In the provided sample, the custom class (named as “Palette”) is created by inheriting the EjsSymbolPalette class. This is the root cause of the reported issue. Since, some of the basic methods are missed in your custom class. 

So, could you please provide us the screenshot or video about your scenario or requirement to create a custom class for Symbol Palette. This will help us to investigate further on your requirement and provide you the appropriate solution at the earliest.

Regards, 
Ramya T

**Comment by endeffects** [comment] 2019-07-01 11:32
Hm, well i'd like to extend the functionality of the EjsSymbolPalette and also i'd like to separate the wire up from the rest of the code. That's why i'm inheriting here. I'm not sure how functions of the base component can get lost in this case. I'm going to test this without the derivation,

**Comment by endeffects** [comment] 2019-07-01 16:45
I tried to the "normal" way to get this done by using the EjsSymbolPalette directly, 
but than i have the issue that the palette can not be resized at runtime. 
I tried to call Refresh() and Render() on the Palette but the width of the palette does not change,
also i still have the issue that the optionalPalette does not render without refreshing the page.

For that reason i started to call the blazor method StateHasChanged() on my derivated class.
For what i have noticed it seems like that you components generally do not support 
the blazor lifecycle methodes except the OnAfterRender() override.

So maybe the error i got is related to this architecture decision and StateHasChanged()
is not supported at all. If this is the case, i need to know how to re-render the palette.

**Comment by RamyaThiru** [comment] 2019-07-02 10:54
Hi,
We have already logged the issue with updating height and width of palette at runtime. We will fix the issue and include it in our Volume 2 main release on mid of July 2019.

The reported issue can be tracked through the below feedback link.
Link: https://www.syncfusion.com/feedback/7237/symbolpalette-size-does-not-updated-due-to-the-value-parsing-issue

Our Syncfusion components support full Blazor lifecycle method. Due to the above reported issue, “StateHasChanged() does not refresh the palette with size changes.

We will get back to you once Volume 2 219 release is rolled out.

Regards,
Ramya T

**Comment by endeffects** [comment] 2019-07-02 11:24
Thank you very much.

**Comment by Sridhar-Narasimhan** [comment] 2020-04-29 08:31
We have fixed this issue in the below feedback link and we are closing this item 

Feedback Link:  https://www.syncfusion.com/feedback/7175/palette-group-instance-gets-duplicated-when-the-palette-group-expands-and

**Closed by Sridhar-Narasimhan** 2020-04-29 08:31 UTC
Labels: bug, diagram
