### ISSUE TITLE
NullReferenceException @ Syncfusion.EJ2.Blazor.BaseAdaptor.BaseRemove

### ISSUE THREAD

**Issue by velreine** [syncfusion/blazor-samples#63] opened 2019-09-17 14:03 UTC
> blazor.server.js:8 Uncaught (in promise) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Syncfusion.EJ2.Blazor.BaseAdaptor.BaseRemove(:44382/String baseData, String keyField, String key)
    at Object.endInvokeDotNetFromJS (blazor.server.js:8)
    at e.<anonymous> (blazor.server.js:8)
    at blazor.server.js:1
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (blazor.server.js:1)
    at e.processIncomingData (blazor.server.js:1)
    at e.connection.onreceive (blazor.server.js:1)
    at WebSocket.i.onmessage (blazor.server.js:1)

I'm getting the following error in Google Chrome's Dev Console when right clicking and pressing 'Delete Record' on a row that is hooked up to our custom data adaptor

Index.razor:

`<EjsGrid TValue="Icecream" AllowSorting="true" AllowExcelExport="true" AllowPdfExport="true" ContextMenuItems="@(new List<object>() { "AutoFit", "AutoFitAll", "SortAscending", "SortDescending","Copy", "Edit", "Delete", "Save", "Cancel","PdfExport", "ExcelExport", "CsvExport", "FirstPage", "PrevPage","LastPage", "NextPage"})" AllowPaging="true" Toolbar="@(new List<string>() { "Search", "Add", "Delete", "Update", "Cancel" })">
            <GridEditSettings AllowAdding="true" AllowDeleting="true" AllowEditing="true" Mode="@EditMode.Normal"></GridEditSettings>
            <Syncfusion.EJ2.Blazor.Data.EjsDataManager AdaptorInstance="@typeof(MyDataAdaptor<Icecream>)" Adaptor="Adaptors.CustomAdaptor" CrossDomain="true"></Syncfusion.EJ2.Blazor.Data.EjsDataManager>
            <GridColumns>
                <GridColumn Field="id" HeaderText="ID" IsPrimaryKey="true" TextAlign="TextAlign.Right" Width="120"></GridColumn>
                <GridColumn Field="name" HeaderText="Name" TextAlign="TextAlign.Right" Width="120"></GridColumn>
                <GridColumn Field="flavor" HeaderText="Flavor" TextAlign="TextAlign.Right" Width="120"></GridColumn>
                <GridColumn Field="color" HeaderText="Color" TextAlign="TextAlign.Right" Width="120"></GridColumn>
                <GridColumn Field="price" HeaderText="Price" TextAlign="TextAlign.Right" Width="120"></GridColumn>`

MyDataAdaptor.cs:

```
public class MyDataAdaptor<TEntity> : DataAdaptor where TEntity : class, new() {

public MyDataAdaptor() { }

public override object Read(DataManagerRequest, string key = null) {
...
}

}

```
It will correctly call the "Read" and "Insert" method and it reads data just fine and insert as well. However trying to rightclick and delete will cause the Grid to "crash" and be stuck in infinite loading animation. 

The "Remove" method is not even called on the server side, it just crashes client side.

Thanks for any help in advance,
Nicky.

**Comment by VigneshNatarajan27** [comment] 2019-09-19 11:19
Greetings from Syncfusion support. 

Query: “I'm getting the following error in Google Chrome's Dev Console when right clicking and pressing 'Delete Record' on a row that is hooked up to our custom data adaptor”

From your query we understand that you are facing issue while deleting a record using context menu item with Custom Adaptor. We have prepared a sample using your code example using our latest version Nuget package (17.2.0.52-beta). We are not able to reproduce the reported issue at our end. Kindly download the sample from below. 

Sample: https://www.syncfusion.com/downloads/support/directtrac/248820/ze/BlazorApp1-1918350454 

To replicate the reported issue at our end, we need the following details.

1.	Share your full Grid rendering code, along with your Remove method.
2.	Share your Nuget package version (xx.x.x.xx-beta). And also ensure that you have referred same version scripts eg . (17.2.52) and Nuget package (17.2.0.52-beta). 
3.	Confirm whether your PrimaryKey value is unique and also type of primaryKey column (int or string)?
4.	If possible try to reproduce the reported issue in provided sample and get back to us. 

Requested details will be helpful for us to validate the reported issue at our end and provide solution as soon as possible.

Regards,
Vignesh Natarajan

**Comment by velreine** [comment] 2019-09-19 12:03
I have uploaded my project to OneDrive on this link: https://1drv.ms/u/s!AsvgV9s0SsdHicM-W0EKQMn5Q5VLHQ?e=8LckN3

There is a reference to an external API that we use for testing.
My problem is that when i set a breakpoint in the "Remove" method of my Adaptor, the breakpoint is never hit. 

And i suspect it is because some of your code is throwing an error.

Hope the provided project is enough.
1: Shared code project.
2: We were using 17.2.0.50, however updating the package did not solve the problem.
3: The primary key is an integer on the Icecream object,

**Comment by VigneshNatarajan27** [comment] 2019-09-26 12:02
Hi Nicky, 

Sorry for the delayed response. 

We have validated your query and we are able to reproduce the reported issue at our end too. The reported issue occur when we change the PropertyName (id) of PrimaryKey column (Id in IceCream class)  We have confirmed it is a bug and logged a defect report “Not able to delete the record properly when JsonProperty attribute defined with different property name” for the same. Fix for the issue will be included in our upcoming Nuget release which is expected to be rolled out on or before 16th October 2019. 

You can track the status of the issue and contact us through the below feedback 

Feedback:  https://www.syncfusion.com/feedback/9110/not-able-to-delete-the-record-properly-when-its-propertyname-is-changed-using-json-attributes 

Till then we appreciate your patience. 

Regards,
Vignesh Natarajan.

**Comment by VigneshNatarajan27** [comment] 2019-10-17 11:32
Hi Nicky, 

We are glad to inform that our latest Nuget package (17.3.0.18-beta) has been successfully rolled out. In this release we have included the fix for the issue “Not able to delete the record properly when JsonProperty attribute defined with different property name”. Please find the latest Nuget package from below  

Nuget: https://www.nuget.org/packages/Syncfusion.EJ2.Blazor/17.3.0.18-beta  

After upgrading, kindly ensure that you have referred latest version of script files 


<link href="https://cdn.syncfusion.com/ej2/**17.3.18**/fabric.css"   rel="stylesheet" />       <script src="https://cdn.syncfusion.com/ej2/**17.3.18**/dist/ej2.min.js"></script>       <script src="https://cdn.syncfusion.com/ej2/**17.3.18**/dist/ejs.interop.min.js"></script>
--

Please get back to us if you have further queries.  

Regards,
Vignesh Natarajan.

**Comment by ajithr** [comment] 2020-12-04 03:27
We are closing this issue since there is no recent activity. Feel free to reopen the issue and update your comments for the reinvestigation.

**Closed by ajithr** 2020-12-04 03:27 UTC
Labels: bug, data-grid
