### ISSUE TITLE
NodePortOffset { X = 0, Y = 0 } seems not to work correctly

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#25] opened 2019-06-16 12:03 UTC
The NodePortOffset { X = 0, Y = 0 } seems not to work correctly.
It centeres the port inside the node. I expected a left and top alignment.

```
// outside the node on the left top
ports.Add(new DiagramPort { Visibility = PortVisibility.Hover, Shape = PortShapes.Square, Offset = new NodePortOffset { X = -0.1, Y = -0.1 } }); 

// inside the node on the left top
ports.Add(new DiagramPort { Visibility = PortVisibility.Hover, Shape = PortShapes.Square, Offset = new NodePortOffset { X = 0.1, Y = 0.1 } }); 

// inside the node centered and middled
ports.Add(new DiagramPort { Visibility = PortVisibility.Hover, Shape = PortShapes.Square, Offset = new NodePortOffset { X = 0, Y = 0 } }); 
```

**Comment by RamyaThiru** [comment] 2019-06-17 10:10
Hi @endeffects ,

Reported issue : Port is not placed properly when specifying (0,0) as its offset.

We have confirmed that the reported issue as a defect. We have logged the defect report for this. The fix for this issue is estimated to be available from our Volume 1 beta release which is tentatively scheduled on  end of June 2019.

Now, you can track the status of your request through the below link.   
Link: https://www.syncfusion.com/feedback/6922/element-does-not-placed-properly-when-specify-the-position-as-0-0

We will get back to you once our Volume 1 beta is released.

Regards,
Ramya T

**Comment by RamyaThiru** [comment] 2019-06-27 10:12
Hi @endeffects ,

Sorry for the inconvenience.

We have fixed the reported issue and we unable to include this fix as scheduled before on Volume 2 beta release due to complexity of the issue. We will include the fix for the reported issue in our Volume 2 main release on July 2019.

We will get back to you once our Volume 2 main release is rolled out.

Regards,
Ramya T

**Comment by endeffects** [comment] 2019-06-27 12:27
Thanks for the feedback :)

**Comment by RamyaThiru** [comment] 2019-07-16 12:59
Hi,

Reported issue : Port is not placed properly when specifying (0,0) as its offset. 

We are glad to announce that our weekly package is released successfully. We have included the fix for the reported issue with this weekly release . Please upgrade to your latest version(17.2.0.34-beta ).

Link: https://www.nuget.org/packages/Syncfusion.EJ2.Blazor/17.2.0.34-beta

Regards,
Ramya T

**Comment by Sridhar-Narasimhan** [comment] 2020-04-29 08:16
We have fixed this issue in the below feedback link and we are closing this item 
https://www.syncfusion.com/feedback/6922/element-does-not-placed-properly-when-specify-the-position-as-0-0

**Closed by Sridhar-Narasimhan** 2020-04-29 08:16 UTC
Labels: bug, diagram
