### ISSUE TITLE
Localization/Globalization error

### ISSUE THREAD

**Issue by julienGrd** [syncfusion/blazor-samples#62] opened 2019-09-11 18:27 UTC
Hi, I actually test yours components to see if it can match my needs for my projects.
I meet a problem with globalization support.
I follow the steps described here https://ej2.syncfusion.com/blazor/documentation/common/globalization/ and here https://ej2.syncfusion.com/blazor/documentation/common/localization/.

I apply this to your test project, i want globalize all the app so i put my code in the MainLayout on the OnAfterRender method.

When I put these line of code
````
if (!firstRender)
        {
            JsRuntime.Ejs().LoadLocaleData("wwwroot/ej2-locale/src/fr.json")
            .LoadCldrData(new string[] { "wwwroot/cldr-data/supplemental/numberingSystems.json", "wwwroot/cldr-data/main/fr/numbers.json", "wwwroot/cldr-data/main/fr/timeZoneNames.json", "wwwroot/cldr-data/main/fr/ca-gregorian.json" })
            .SetCulture("fr").SetCurrencyCode("EUR");
        }
````
I have a crash in js on the first page
````
Error: There was an error applying batch 13.
e.log @ blazor.server.js:15

followed by
Uncaught (in promise) TypeError: Cannot read property 'ownerDocument' of null
    at e.updateComponent (blazor.server.js:8)
    at Object.t.renderBatch (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:15)
    at blazor.server.js:15
    at Object.next (blazor.server.js:15)
    at blazor.server.js:15
    at new Promise (<anonymous>)
    at r (blazor.server.js:15)
    at e.processBatch (blazor.server.js:15)
    at e.<anonymous> (blazor.server.js:8)

````

All the translation files asked exist in the wwwroot folder as described in your docs

this make the app unusable (nothing respond).

can you check that ? 

thanks !

Julien

**Comment by sridurgha** [comment] 2019-09-13 11:45
Hi @julienGrd ,

Greetings from Syncfusion.

We have validated the reported query and found that in the code snippet mentioned, you have used the condition which allows localization/globalization translation only when firstRender turns out be false. This is the cause for prevention of localized/globalized text.

However, we have created a sample for your reference and the same can be found from the below link. 

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/248218/ze/grid762297861.zip 

Please get back to us if we misunderstood your query with clear description of error, scenario and screenshot.

Regards,
Sridurgha U

**Comment by julienGrd** [comment] 2019-09-13 15:39
Hi Sridurgha and thanks for your quick response !

It seem the problem is more when i use this code in the AfterRender of the mainLayout. I wanted to do this for set the culture for all the app but maybe it's not how it works.

In your attachment project, i can put this code on the mainLayout and its works (but i can't check if with navigation the culture will stay because there is only one page), but not in your blazor sample solution (i fall on the same error, event without the !firstRender).

Can you clarify some points ? :
- if i want set culture for all the app, is this the good way ? (layout). Or i need to call this code for all of my components ? (and maybe make a baseComponent wich called this code and inherits all my component of this BaseComponent). Ideally, can you provide an example to make all the app localized ?
- It seem the EUR currency not work, i still have the $ (i'm using the fr localization with this code)
````
JsRuntime.Ejs().LoadLocaleData("wwwroot/ej2-locale/src/fr.json")
        .LoadCldrData(new string[] { "wwwroot/cldr-data/supplemental/numberingSystems.json", "wwwroot/cldr-data/main/fr/numbers.json", "wwwroot/cldr-data/main/fr/timeZoneNames.json", "wwwroot/cldr-data/main/fr/ca-gregorian.json" })
        .SetCulture("fr").SetCurrencyCode("EUR");
````


PS : I also open a feeback https://www.syncfusion.com/feedback/8815/localization-globalization-error-on-blazor-github-sample

**Comment by sridurgha** [comment] 2019-09-16 12:40
Hi @julienGrd ,

**Query 1: if i want set culture for all the app, is this the good way ? (layout). Or i need to call this code for all of my components ? (and maybe make a baseComponent wich called this code and inherits all my component of this BaseComponent). Ideally, can you provide an example to make all the app localized ?**

Yes, we can set the culture to the whole app by using SetCulture() method in MainLayout.razor page. This method will change the culture to all components in the app. We have created a sample considering your requirement and the same can be referred from the below link.

**Sample Link: https://www.syncfusion.com/downloads/support/directtrac/248218/ze/localization-931812896.zip**

**Query 2: It seem the EUR currency not work, i still have the $ (i'm using the fr localization with this code)**

In order to change the currency format, the corresponding currencies.json file is also need to be loaded in the application. For example, If EUR currency is needed in fr localization then we need to refer the currencies.json file from fr locale files. Kindly refer the below code example for your reference.

```   protected override void OnAfterRender(bool firstRender)
    {
        this.JsRuntime.Ejs().LoadLocaleData("wwwroot/ej2-locale/src/fr.json").LoadCldrData(new string[] { "wwwroot/cldr-data/supplemental/numberingSystems.json", "wwwroot/cldr-data/main/fr/numbers.json", "wwwroot/cldr-data/main/fr/timeZoneNames.json", "wwwroot/cldr-data/main/fr/ca-gregorian.json", "wwwroot/cldr-data/main/fr/currencies.json" }).SetCulture("fr").SetCurrencyCode("EUR");
    }
```

However, we will include this in our documentation and the changes will be included in our upcoming biweekly patch release.

Regards,
Sridurgha U

**Comment by ajithr** [comment] 2020-02-28 09:58
Hi @julienGrd ,

We have published the content for configuring currency code to all Syncfusion Blazor components in our documentation. Please refer to the below link for more details.

https://ej2.syncfusion.com/blazor/documentation/common/globalization/

Please get back to us if you need any further assistance with this.

Regards,
Ajith R

**Closed by ajithr** 2020-02-28 09:58 UTC
Labels: common
